version: '3'

services:
  db:
    image: postgres:latest
    networks:
      - db_network
    volumes:
      - city_orient_db_volume:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.local.db

  backend:
    build: ./backend
    command: >
      bash -c "sleep 5 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --bind :8000 --reload city_orient_backend.wsgi:application"
    depends_on:
      - db
    volumes:
      - ./backend/src:/src
      - media_volume:/media
    networks:
      - nginx_network
      - db_network
    env_file:
      - ./backend/.env.local

  frontend:
    build: ./frontend
    command: npm run local
    depends_on:
      - backend
    networks:
      - nginx_network
    volumes:
      - ./frontend/src:/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:1.13
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./nginx/local:/etc/nginx/conf.d
      - ./backend/static:/static
      - media_volume:/media
    depends_on:
      - backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  city_orient_db_volume:
  media_volume:
